[redis]
addr="172.20.99.99:6379"
db=10

[global]
listen="0.0.0.0:18000"
mode="production" # production | consumer
dockerendpoint="tcp://172.20.99.99:2375"
target=["172.16.32.32:5000"]

# 配置用于push成功后确认是否存在，和target一样，后期会去掉这个结构体，这里重复了
[registry]
url=["http://172.16.32.32:5000"]
username=""
password=""
